AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../create-task/
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        CreateTask:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
